spring:
  jpa:
    hibernate:
      dll-auto: create-drop
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    database-platform: org.hibernate.dialect.H2Dialect

---

h2:
  console:
    enabled: "true"

