spring:
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      dll-auto: create-drop
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    database-platform: org.hibernate.dialect.H2Dialect

---

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    root: warn
    org:
      hibernate:
        0: warn
        SQL: warn

---

h2:
  console:
    enabled: "true"

